language: elixir
elixir:
  - 1.4.5
otp_release:
  - 20.0
env:
  - MIX_ENV=test
services:
  - postgresql
  - redis
before_script:
  - psql -c 'create database esioci;' -U postgres
script:
  - mix deps.get
  - mix compile
  - mix ecto.create
  - mix ecto.migrate
  - mix run priv/repo/seeds.exs
  - mix coveralls.travis
